- Package.swift
Update for the 2.25.1 release 
N/a
[VIDCS-859](https://jira.vonage.com/browse/VIDCS-859)
> VIDCS-859: Update for the 2.25.1 release 

- Package.swift
Update for 2.25.2 version
Update for 2.25.2 version
[VIDCS-905](https://jira.vonage.com/browse/VIDCS-905)
> VIDCS-905: Update for 2.25.2 version

- Package.swift
Added the dependency "Accelerate"
N/A
[VIDCS-905](https://jira.vonage.com/browse/VIDCS-905)
> VIDCS-905:Added the dependency

- Package.swift
Update version to 2.25.3
N/A
[VIDCS-1071](https://jira.vonage.com/browse/VIDCS-1071)
> VIDCS-1071:Update version to 2.25.3

- Package.swift
[VIDCS-](https://jira.vonage.com/browse/VIDCS-)
> * Update to 2.26.0 version

- Package.swift
Update to 2.26.1 version
n/a
[VIDCS-1438](https://jira.vonage.com/browse/VIDCS-1438)
> VIDCS-1438 : Update to 2.26.1 version

- Package.swift
Update to 2.26.2
n/a
[VIDCS-1586](https://jira.vonage.com/browse/VIDCS-1586)
> VIDCS-1586 : Update to 2.26.2

- Package.swift
Updates for release 2.27.0
n/a
n/a
> Updates for release 2.27.0

- Package.swift
- README.md
Update the version to 2.27.1
n/a
[VIDCS-1833](https://jira.vonage.com/browse/VIDCS-1833)
> VIDCS-1833:Update the version to 2.27.1

- Package.swift
- README.md
Update version to 2.27.2
n/a
[VIDCS-1993](https://jira.vonage.com/browse/VIDCS-1993)
> VIDCS-1993: Update version to 2.27.2

- Package.swift
Update version to 2.27.3
n/a
[VIDCS-2111](https://jira.vonage.com/browse/VIDCS-2111)
> VIDCS-2111: Update version to 2.27.3

- Package.swift
VIDCS-2113: Update version to 2.26.3
[VIDCS-2113](https://jira.vonage.com/browse/VIDCS-2113)
> VIDCS-2113: Update version to 2.26.3

- Package.swift
VIDCS-2114: Update version to 2.25.5
[VIDCS-2114](https://jira.vonage.com/browse/VIDCS-2114)
> VIDCS-2114: Update version to 2.25.5

- Package.swift
Update version to 2.27.4
n/a
[VIDCS-2327](https://jira.vonage.com/browse/VIDCS-2327)
> VIDCS-2327:Update version to 2.27.4

- Package.swift
Update version to 2.28.0
n/a
[VIDCS-2374](https://jira.vonage.com/browse/VIDCS-2374)
> VIDCS-2374: Update version to 2.28.0

- Package.swift
Update package to version 2.28.1
n/a
[VIDCS-2594](https://jira.vonage.com/browse/VIDCS-2594)
> VIDCS-2594: Update package to version 2.28.1

- Package.swift
Upgarde to 2.28.2 version
n/a
[VIDCS-2726](https://jira.vonage.com/browse/VIDCS-2726)
> VIDCS-2726:Upgarde to 2.28.2 version

- Package.swift
Update to 2.28.3 version
n/a
[VIDCS-3112](https://jira.vonage.com/browse/VIDCS-3112)
> VIDCS-3112: Update to 2.28.3 version

- Package.swift
SPM release for 2.29.0
N/A
[VIDCS-3096](https://jira.vonage.com/browse/VIDCS-3096)
> chetan/VIDCS-3096: SPM release for 2.29.0

- Package.swift
- README.md
- release-notes.md
Update the documentation and build to 2.29.0
n/a
[VIDCS-](https://jira.vonage.com/browse/VIDCS-3360)
> VIDCS-3360 : Update the documentation and build to 2.29.0

- Package.swift
Update the version to 2.29.1
n/a
[VIDCS-3436](https://jira.vonage.com/browse/VIDCS-3436)
> VIDCS-3436 : Update the version to 2.29.1

- Package.swift
Release 2.28.4 version
n/a
[VIDCS-3450](https://jira.vonage.com/browse/VIDCS-3450)
> VIDCS-3450: Release 2.28.4 version

- Package.swift
Update the version for 2.28.4 release
n/a
[VIDCS-](https://jira.vonage.com/browse/VIDCS-3450)
> Update the version for 2.28.4 release

- Package.swift
Update version to 2.30.0
n/a
[VIDCS-3598](https://jira.vonage.com/browse/VIDCS-3598)
> VIDCS-3598: Update version to 2.30.0

- Package.swift
Update version to 2.30.1
n/a
[VIDCS-3757](https://jira.vonage.com/browse/VIDCS-3757)
> VIDCS-3757: Update version to 2.30.1
